
DROP TABLE IF EXISTS CMM_CLIENT;
CREATE TABLE CMM_CLIENT (
       idx int PRIMARY KEY AUTO_INCREMENT,
       name varchar(30) NOT NULL default '',
       UNIQUE(name)
);

INSERT INTO CMM_CLIENT (name) VALUES ('CNA');
INSERT INTO CMM_CLIENT (name) VALUES ('Careflash');
INSERT INTO CMM_CLIENT (name) VALUES ('RLG');
INSERT INTO CMM_CLIENT (name) VALUES ('Northside');
INSERT INTO CMM_CLIENT (name) VALUES ('SNTS');
